11.27.2023 09:23:26 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:23:26 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:23:26 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:23:27 WARNING  * Debugger is active!
11.27.2023 09:23:27 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:25:26 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:25:26 INFO 127.0.0.1 - - [27/Nov/2023 09:25:26] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:25:26 INFO 127.0.0.1 - - [27/Nov/2023 09:25:26] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:26:39 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:26:39 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:26:39 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:26:39 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:26:39 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:26:39 WARNING  * Debugger is active!
11.27.2023 09:26:39 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:26:43 INFO 127.0.0.1 - - [27/Nov/2023 09:26:43] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:26:43 INFO 127.0.0.1 - - [27/Nov/2023 09:26:43] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:31:09 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:31:09 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:31:09 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:31:10 WARNING  * Debugger is active!
11.27.2023 09:31:10 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:31:14 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:31:14 INFO 127.0.0.1 - - [27/Nov/2023 09:31:14] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:31:14 INFO 127.0.0.1 - - [27/Nov/2023 09:31:14] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:32:15 INFO 127.0.0.1 - - [27/Nov/2023 09:32:15] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:32:15 INFO 127.0.0.1 - - [27/Nov/2023 09:32:15] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:33:15 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:33:15 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:33:15 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:33:15 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:33:16 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:33:16 WARNING  * Debugger is active!
11.27.2023 09:33:16 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:34:55 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:34:55 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:34:55 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:34:55 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:34:56 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:34:56 WARNING  * Debugger is active!
11.27.2023 09:34:56 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:35:17 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:35:17 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:35:17 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:35:17 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:35:18 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:35:18 WARNING  * Debugger is active!
11.27.2023 09:35:18 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:40:16 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:40:16 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:40:16 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:40:16 WARNING  * Debugger is active!
11.27.2023 09:40:16 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:40:24 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:40:24 INFO 127.0.0.1 - - [27/Nov/2023 09:40:24] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:40:24 INFO 127.0.0.1 - - [27/Nov/2023 09:40:24] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:40:48 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:40:48 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:40:48 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:40:49 WARNING  * Debugger is active!
11.27.2023 09:40:49 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:40:53 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:40:53 INFO 127.0.0.1 - - [27/Nov/2023 09:40:53] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:40:53 INFO 127.0.0.1 - - [27/Nov/2023 09:40:53] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:41:28 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:41:28 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:41:28 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:41:28 WARNING  * Debugger is active!
11.27.2023 09:41:28 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:41:30 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py", line 83, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 208, in login
    return self._login("login", (user_id, password, url, connection), session_id, pin, session_status_callback,
  File "/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/ForexConnect.py", line 131, in _login
    self._session.use_table_manager(fxcorepy.O2GTableManagerMode.YES,
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 09:41:30 INFO 127.0.0.1 - - [27/Nov/2023 09:41:30] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:41:31 INFO 127.0.0.1 - - [27/Nov/2023 09:41:31] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:43:44 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:43:44 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:43:44 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:43:45 WARNING  * Debugger is active!
11.27.2023 09:43:45 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:43:48 INFO 127.0.0.1 - - [27/Nov/2023 09:43:48] "[35m[1mPOST /getPH HTTP/1.1[0m" 500 -
11.27.2023 09:44:42 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:44:42 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:44:42 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:44:43 WARNING  * Debugger is active!
11.27.2023 09:44:43 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:44:45 INFO 127.0.0.1 - - [27/Nov/2023 09:44:45] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:45:11 INFO 127.0.0.1 - - [27/Nov/2023 09:45:11] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:45:11 INFO 127.0.0.1 - - [27/Nov/2023 09:45:11] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:45:22 INFO 127.0.0.1 - - [27/Nov/2023 09:45:22] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:45:22 INFO 127.0.0.1 - - [27/Nov/2023 09:45:22] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:48:54 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 09:48:54 INFO [33mPress CTRL+C to quit[0m
11.27.2023 09:48:54 INFO  * Restarting with watchdog (inotify)
11.27.2023 09:48:55 WARNING  * Debugger is active!
11.27.2023 09:48:55 INFO  * Debugger PIN: 782-690-144
11.27.2023 09:49:17 INFO 127.0.0.1 - - [27/Nov/2023 09:49:17] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:49:17 INFO 127.0.0.1 - - [27/Nov/2023 09:49:17] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:49:18 INFO 127.0.0.1 - - [27/Nov/2023 09:49:18] "POST /getPH_from_filestore HTTP/1.1" 200 -
11.27.2023 09:51:16 INFO 127.0.0.1 - - [27/Nov/2023 09:51:16] "POST /getPH HTTP/1.1" 200 -
11.27.2023 09:51:16 INFO 127.0.0.1 - - [27/Nov/2023 09:51:16] "GET /mk_fn?instrument=EUR/USD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 09:51:16 INFO 127.0.0.1 - - [27/Nov/2023 09:51:16] "POST /getPH_from_filestore HTTP/1.1" 200 -
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/__main__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTTDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtbtetl1.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTCDS.test.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/PDSServicePto2211.cli.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTLoader.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTImage.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtbtetl2.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtfxcommon.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTCDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtcli.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTPDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtetl.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTADS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTIDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTFXCMWrapper.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTPDS.test.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTPDHelper.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtfxc.test.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtfxc.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtconstants.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTConfig.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTCloudFS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTCore.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtdotenv.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtflags.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtcommon/common.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtcommon/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/ResponseListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/x-pyd.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/errors.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/ForexConnect.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/EachRowListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/common.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/LiveHistory.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/TableListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/TableManagerListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/SessionStatusListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/lib/linux/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/lib/windows/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/__main__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTTDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtbtetl1.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTCDS.test.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/PDSServicePto2211.cli.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTLoader.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTImage.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtbtetl2.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxcommon.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTCDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtcli.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTPDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtetl.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTADS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTIDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTFXCMWrapper.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTPDS.test.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTPDHelper.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.test.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtfxc.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtconstants.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTConfig.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTCloudFS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/JGTCore.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtdotenv.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtflags.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtcommon/common.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/jgtcommon/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/EachRowListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/common.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/LiveHistory.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/TableListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/TableManagerListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/SessionStatusListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/jgtpy/forexconnect/lib/windows/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/__main__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTTDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtcommon/common.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtcommon/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtbtetl1.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTCDS.test.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/PDSServicePto2211.cli.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTLoader.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTImage.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtbtetl2.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtfxcommon.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTCDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtcli.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTPDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtetl.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTADS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTIDS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/ResponseListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/x-pyd.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/errors.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/ForexConnect.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/lib/linux/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/lib/windows/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/EachRowListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/common.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/LiveHistory.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/TableListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/TableManagerListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/forexconnect/SessionStatusListener.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTFXCMWrapper.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTPDS.test.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTPDHelper.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtfxc.test.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtfxc.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtconstants.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTConfig.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/__init__.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTCloudFS.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/JGTCore.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtdotenv.py', reloading
11.27.2023 09:57:32 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy310/lib/python3.10/site-packages/~gtpy/jgtflags.py', reloading
11.27.2023 09:57:32 INFO  * Restarting with watchdog (inotify)
11.27.2023 10:13:12 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 10:13:12 INFO [33mPress CTRL+C to quit[0m
11.27.2023 10:13:12 INFO  * Restarting with watchdog (inotify)
11.27.2023 10:13:12 WARNING  * Debugger is active!
11.27.2023 10:13:12 INFO  * Debugger PIN: 687-098-907
11.27.2023 10:13:52 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pip/_vendor/pyparsing/core.py', reloading
11.27.2023 10:13:52 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pip/_vendor/packaging/markers.py', reloading
11.27.2023 10:13:53 INFO  * Restarting with watchdog (inotify)
11.27.2023 10:15:57 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 10:15:57 INFO [33mPress CTRL+C to quit[0m
11.27.2023 10:15:57 INFO  * Restarting with watchdog (inotify)
11.27.2023 10:15:58 WARNING  * Debugger is active!
11.27.2023 10:15:58 INFO  * Debugger PIN: 687-098-907
11.27.2023 10:16:40 INFO 127.0.0.1 - - [27/Nov/2023 10:16:40] "POST /getPH HTTP/1.1" 200 -
11.27.2023 10:16:40 INFO 127.0.0.1 - - [27/Nov/2023 10:16:40] "GET /mk_fn?instrument=EUR%2FUSD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 10:16:41 INFO 127.0.0.1 - - [27/Nov/2023 10:16:41] "POST /getPH_from_filestore HTTP/1.1" 200 -
11.27.2023 10:16:41 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/jgtcli.py', reloading
11.27.2023 10:16:41 INFO 127.0.0.1 - - [27/Nov/2023 10:16:41] "POST /run_jgtcli HTTP/1.1" 200 -
11.27.2023 10:16:42 INFO  * Restarting with watchdog (inotify)
11.27.2023 10:16:42 WARNING  * Debugger is active!
11.27.2023 10:16:42 INFO  * Debugger PIN: 687-098-907
11.27.2023 10:18:32 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 10:18:32 INFO [33mPress CTRL+C to quit[0m
11.27.2023 10:18:32 INFO  * Restarting with watchdog (inotify)
11.27.2023 10:18:33 WARNING  * Debugger is active!
11.27.2023 10:18:33 INFO  * Debugger PIN: 687-098-907
11.27.2023 10:59:44 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 10:59:44 INFO [33mPress CTRL+C to quit[0m
11.27.2023 10:59:44 INFO  * Restarting with watchdog (inotify)
11.27.2023 10:59:45 WARNING  * Debugger is active!
11.27.2023 10:59:45 INFO  * Debugger PIN: 687-098-907
11.27.2023 10:59:49 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/jgtfxc.py', reloading
11.27.2023 10:59:49 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/jgtfxc.py", line 84, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py", line 209, in login
    use_table_manager, table_manager_callback)
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py", line 132, in _login
    self._table_manager_listener)
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 10:59:49 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py', reloading
11.27.2023 10:59:49 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/flask/app.py', reloading
11.27.2023 10:59:49 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/pdsserver.py', reloading
11.27.2023 10:59:49 INFO 127.0.0.1 - - [27/Nov/2023 10:59:49] "[35m[1mPOST /getPH HTTP/1.1[0m" 500 -
11.27.2023 10:59:49 INFO 127.0.0.1 - - [27/Nov/2023 10:59:49] "GET /mk_fn?instrument=EUR%2FUSD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 10:59:49 INFO  * Restarting with watchdog (inotify)
11.27.2023 10:59:50 WARNING  * Debugger is active!
11.27.2023 10:59:50 INFO  * Debugger PIN: 687-098-907
11.27.2023 10:59:50 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/jgtfxc.py", line 84, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py", line 209, in login
    use_table_manager, table_manager_callback)
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py", line 132, in _login
    self._table_manager_listener)
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 10:59:50 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/jgtfxc.py', reloading
11.27.2023 10:59:50 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py', reloading
11.27.2023 10:59:50 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/flask/app.py', reloading
11.27.2023 10:59:50 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/pdsserver.py', reloading
11.27.2023 10:59:50 INFO 127.0.0.1 - - [27/Nov/2023 10:59:50] "[35m[1mPOST /getPH HTTP/1.1[0m" 500 -
11.27.2023 10:59:50 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pandas/util/_decorators.py', reloading
11.27.2023 10:59:50 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pandas/util/_decorators.py', reloading
11.27.2023 10:59:50 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pandas/io/json/_json.py', reloading
11.27.2023 10:59:50 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pandas/io/json/_json.py', reloading
11.27.2023 10:59:50 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pandas/io/json/_json.py', reloading
11.27.2023 10:59:51 INFO  * Restarting with watchdog (inotify)
11.27.2023 10:59:52 WARNING  * Debugger is active!
11.27.2023 10:59:52 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:01:29 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 11:01:29 INFO [33mPress CTRL+C to quit[0m
11.27.2023 11:01:29 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:01:30 WARNING  * Debugger is active!
11.27.2023 11:01:30 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:03:20 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 11:03:20 INFO [33mPress CTRL+C to quit[0m
11.27.2023 11:03:20 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:03:21 WARNING  * Debugger is active!
11.27.2023 11:03:21 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:03:34 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 11:03:34 INFO [33mPress CTRL+C to quit[0m
11.27.2023 11:03:34 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:03:35 WARNING  * Debugger is active!
11.27.2023 11:03:35 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:04:08 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 11:04:08 INFO [33mPress CTRL+C to quit[0m
11.27.2023 11:04:08 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:04:09 WARNING  * Debugger is active!
11.27.2023 11:04:09 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:06:09 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 11:06:09 INFO [33mPress CTRL+C to quit[0m
11.27.2023 11:06:09 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:06:09 WARNING  * Debugger is active!
11.27.2023 11:06:09 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:07:43 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 11:07:43 INFO [33mPress CTRL+C to quit[0m
11.27.2023 11:07:43 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:07:44 WARNING  * Debugger is active!
11.27.2023 11:07:44 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:08:02 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 11:08:02 INFO [33mPress CTRL+C to quit[0m
11.27.2023 11:08:02 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:08:03 WARNING  * Debugger is active!
11.27.2023 11:08:03 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:10:59 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 11:10:59 INFO [33mPress CTRL+C to quit[0m
11.27.2023 11:10:59 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:10:59 WARNING  * Debugger is active!
11.27.2023 11:10:59 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:11:25 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
11.27.2023 11:11:25 INFO [33mPress CTRL+C to quit[0m
11.27.2023 11:11:25 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:11:26 WARNING  * Debugger is active!
11.27.2023 11:11:26 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:11:33 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/jgtfxc.py', reloading
11.27.2023 11:11:33 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/jgtfxc.py", line 90, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py", line 215, in login
    use_table_manager, table_manager_callback)
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py", line 138, in _login
    self._table_manager_listener)
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 11:11:33 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py', reloading
11.27.2023 11:11:33 INFO 127.0.0.1 - - [27/Nov/2023 11:11:33] "[35m[1mPOST /getPH HTTP/1.1[0m" 500 -
11.27.2023 11:11:33 INFO 127.0.0.1 - - [27/Nov/2023 11:11:33] "GET /mk_fn?instrument=EUR%2FUSD&timeframe=m1&ext=csv HTTP/1.1" 200 -
11.27.2023 11:11:33 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:11:34 WARNING  * Debugger is active!
11.27.2023 11:11:34 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:11:35 ERROR Exception: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)
Traceback (most recent call last):
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/jgtfxc.py", line 90, in login_forexconnect
    fx.login(user_id=user_id,password=password,url=url,connection=connection, pin="", session_id="", session_status_callback=jgtfxcommon.session_status_changed)
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py", line 215, in login
    use_table_manager, table_manager_callback)
  File "/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py", line 138, in _login
    self._table_manager_listener)
Boost.Python.ArgumentError: Python argument types in
    None.use_table_manager(O2GSession, O2GTableManagerMode, TableManagerListener)
did not match C++ signature:
    use_table_manager(IO2GSession*, O2GTableManagerMode, boost::shared_ptr<fxcore2::python::O2GTableManagerListenerImpl>)

11.27.2023 11:11:35 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/pdsserver.py', reloading
11.27.2023 11:11:35 INFO 127.0.0.1 - - [27/Nov/2023 11:11:35] "[35m[1mPOST /getPH HTTP/1.1[0m" 500 -
11.27.2023 11:11:35 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/jgtfxc.py', reloading
11.27.2023 11:11:35 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/jgtpy/forexconnect/ForexConnect.py', reloading
11.27.2023 11:11:35 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/flask/app.py', reloading
11.27.2023 11:11:35 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pandas/util/_decorators.py', reloading
11.27.2023 11:11:35 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pandas/io/json/_json.py', reloading
11.27.2023 11:11:36 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:11:36 WARNING  * Debugger is active!
11.27.2023 11:11:36 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:46:35 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTCore.py', reloading
11.27.2023 11:46:35 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:46:36 WARNING  * Debugger is active!
11.27.2023 11:46:36 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:56:58 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTCore.py', reloading
11.27.2023 11:56:58 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTCore.py', reloading
11.27.2023 11:56:58 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/__init__.py', reloading
11.27.2023 11:56:58 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/ForexConnect.py', reloading
11.27.2023 11:56:58 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/__init__.py', reloading
11.27.2023 11:56:58 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtfxc.py', reloading
11.27.2023 11:56:58 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/pdsserver.py', reloading
11.27.2023 11:56:59 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:56:59 WARNING  * Debugger is active!
11.27.2023 11:56:59 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:57:04 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/__init__.py', reloading
11.27.2023 11:57:04 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtflags.py', reloading
11.27.2023 11:57:04 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtetl.py', reloading
11.27.2023 11:57:04 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTCore.py', reloading
11.27.2023 11:57:04 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:57:05 WARNING  * Debugger is active!
11.27.2023 11:57:05 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:57:12 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/__init__.py', reloading
11.27.2023 11:57:12 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtflags.py', reloading
11.27.2023 11:57:12 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtetl.py', reloading
11.27.2023 11:57:12 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTCore.py', reloading
11.27.2023 11:57:12 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/__init__.py', reloading
11.27.2023 11:57:12 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/lib/linux/__init__.py', reloading
11.27.2023 11:57:12 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:57:13 WARNING  * Debugger is active!
11.27.2023 11:57:13 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTADS.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTCDS.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTCDS.test.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTCloudFS.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTConfig.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTCore.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTFXCMWrapper.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTIDS.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTImage.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTLoader.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTPDHelper.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTPDS.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTPDS.test.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/JGTTDS.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/PDSServicePto2211.cli.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/__init__.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/__main__.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/fsserver.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtbtetl1.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtbtetl2.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtcli.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtconstants.py', reloading
11.27.2023 11:57:14 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtdotenv.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtetl.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtflags.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtfxc.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtfxc.test.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/jgtfxcommon.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/pdsserver.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/EachRowListener.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/ForexConnect.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/LiveHistory.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/ResponseListener.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/SessionStatusListener.py', reloading
11.27.2023 11:57:15 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/forexconnect/TableListener.py', reloading
11.27.2023 11:57:15 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:57:16 WARNING  * Debugger is active!
11.27.2023 11:57:16 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:57:17 INFO  * Detected change in '/mnt/c/usr/src/_jgt/jgtpy2311/jgtpy/__init__.py', reloading
11.27.2023 11:57:18 INFO  * Restarting with watchdog (inotify)
11.27.2023 11:57:19 WARNING  * Debugger is active!
11.27.2023 11:57:19 INFO  * Debugger PIN: 687-098-907
11.27.2023 11:58:20 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pip/_vendor/pyparsing/core.py', reloading
11.27.2023 11:58:20 INFO  * Detected change in '/home/jgi/anaconda3/envs/jgtpy-pypi/lib/python3.7/site-packages/pip/_vendor/packaging/markers.py', reloading
11.27.2023 11:58:20 INFO  * Restarting with watchdog (inotify)
